const role = [
    "Phòng Công tác học sinh sinh viên (CTHSSV)",
    "Phòng Đại học",
    "Phòng Sau đại học",
    "Phòng điện toán và máy tính",
    "Phòng khảo thí và kiểm định chất lượng",
    "Phòng tài chính",
    "TDT Creative Language Center",
    "Trung tâm tin học",
    "Trung tâm đào tạo phát triển xã hội (SDTC)",
    "Trung tâm phát triển Khoa học quản lý và Ứng dụng công nghệ (ATEM)",
    "Trung tâm hợp tác doanh nghiệp và cựu sinh viên",
    "Khoa Luật",
    "Trung tâm ngoại ngữ - tin học - bồi dưỡng văn hóa",
    "Viện chính sách kinh tế và kinh doanh",
    "Khoa Mỹ thuật công nghiệp",
    "Khoa Điện - Điện tử",
    "Khoa Công nghệ thông tin",
    "Khoa Quản trị kinh doanh",
    "Khoa Môi trường và bảo hộ lao động",
    "Khoa Lao động công đoàn",
    "Khoa Tài chính ngân hàng",
    "Khoa giáo dục quốc tế",
];

module.exports = role;